server {
    listen       3000;
    server_name  localhost;

    # 关闭nginx版本号
    server_tokens    off;
    # 统一设置全局root
    root    /usr/share/nginx/html;

    #access_log  /var/log/nginx/host.access.log  main;

    # 设置静态文件缓存策略
    location ~* \.(html|htm)$ {
        add_header Cache-Control "no-store, no-cache";
    }
    location ~ .*\.(js|css)$ {
        expires 365d;
        add_header Cache-Control "public, no-transform";
    }
    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|txt)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
    # 定义服务访问配置
    location /sei-online-code-web {
        try_files  $uri /sei-online-code-web/index.html;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
