package com.changhong.onlinecode.agent;

import org.slf4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Codex 沙箱配置写入器（PR1）。参考 multica
 * {@code server/internal/daemon/execenv/codex_sandbox.go} 的 managed-block 模型。
 *
 * <p>在 per-run {@code CODEX_HOME/config.toml} 顶部写一个 marker 分隔的托管块，
 * 幂等（已存在则先剥后写），marker 之外的用户内容保留。policy 按平台分流：</p>
 * <ul>
 *   <li>非-darwin（Linux 等）：{@code sandbox_mode="workspace-write"} + {@code [sandbox_workspace_write] network_access=true}。
 *       Linux Landlock 不受 macOS Seatbelt 的 network_access 静默忽略 bug 影响。</li>
 *   <li>darwin：{@code sandbox_mode="danger-full-access"}。因 openai/codex#10390——
 *       macOS Seatbelt 在 workspace-write 模式下静默忽略 network_access=true，
 *       DNS 在 syscall 层被拦，agent 无法触达外部 API，故回退全访问。</li>
 * </ul>
 *
 * <p>PR1 仅含 sandbox 块；memory/multi_agent/skill_strip/user_skills/home-link/MCP
 * 属后续 PR（见 docs/plan/MULTI-CLI-RUNNER.md）。</p>
 *
 * @author sei-online-code
 */
public final class CodexSandboxConfig {

    static final String BEGIN_MARKER = "# BEGIN sei-managed (do not edit; regenerated by CodexSandboxConfig)";
    static final String END_MARKER = "# END sei-managed";

    private CodexSandboxConfig() {
    }

    /**
     * 在给定 codex-home 下写/重写托管沙箱块。
     *
     * @param codexHome per-run CODEX_HOME 目录（不存在则创建）
     * @param logger    日志器（darwin 回退时 warn）
     * @throws IOException 读写 config.toml 失败
     */
    public static void write(Path codexHome, Logger logger) throws IOException {
        Files.createDirectories(codexHome);
        Path config = codexHome.resolve("config.toml");
        String existing = Files.exists(config) ? Files.readString(config, StandardCharsets.UTF_8) : "";
        String stripped = stripManagedBlock(existing);
        String block = buildBlock(logger);
        String content = block + "\n" + stripped;
        Files.writeString(config, content, StandardCharsets.UTF_8);
    }

    /** 是否走 darwin（macOS）的 danger-full-access 回退策略。包级可见便于测试。 */
    static boolean isDarwin() {
        String os = System.getProperty("os.name", "");
        String lower = os.toLowerCase();
        return lower.contains("mac") || lower.contains("darwin");
    }

    private static String buildBlock(Logger logger) {
        StringBuilder sb = new StringBuilder();
        sb.append(BEGIN_MARKER).append('\n');
        if (isDarwin()) {
            sb.append("sandbox_mode = \"danger-full-access\"\n");
            if (logger != null) {
                logger.warn("codex sandbox: darwin 检测到，回退 danger-full-access（openai/codex#10390）");
            }
        } else {
            sb.append("sandbox_mode = \"workspace-write\"\n");
            sb.append("[sandbox_workspace_write]\n");
            sb.append("network_access = true\n");
        }
        sb.append(END_MARKER);
        return sb.toString();
    }

    /** 剥离既有托管块（含其后同行到 END_MARKER 行）。幂等。 */
    private static String stripManagedBlock(String content) {
        int begin = content.indexOf(BEGIN_MARKER);
        if (begin < 0) {
            return content;
        }
        int end = content.indexOf(END_MARKER, begin);
        if (end < 0) {
            // 无 END 异常：剥到串尾
            return content.substring(0, begin);
        }
        int lineEnd = content.indexOf('\n', end);
        String after = lineEnd >= 0 ? content.substring(lineEnd + 1) : "";
        return content.substring(0, begin) + after;
    }
}
