package com.changhong.onlinecode.agent;

import org.slf4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.stream.Stream;

/**
 * Codex 沙箱配置写入器（PR1）。参考 multica
 * {@code server/internal/daemon/execenv/codex_sandbox.go} 的 managed-block 模型。
 *
 * <p>在 per-run {@code CODEX_HOME/config.toml} 顶部写一个 marker 分隔的托管块，
 * 幂等（已存在则先剥后写），marker 之外的用户内容保留。policy 按平台分流：</p>
 * <ul>
 *   <li>非-darwin（Linux 等）：{@code sandbox_mode="workspace-write"} + {@code [sandbox_workspace_write] network_access=true}。
 *       Linux Landlock 不受 macOS Seatbelt 的 network_access 静默忽略 bug 影响。</li>
 *   <li>darwin：{@code sandbox_mode="danger-full-access"}。因 openai/codex#10390——
 *       macOS Seatbelt 在 workspace-write 模式下静默忽略 network_access=true，
 *       DNS 在 syscall 层被拦，agent 无法触达外部 API，故回退全访问。</li>
 * </ul>
 *
 * <p>PR1 写 sandbox 块；PR2 增补 memory/multi_agent 禁用键（{@link #buildBlock}）、
 * skill_strip（{@link #stripSkillsConfig}）、user_skills 播种（{@link #seedUserSkills}）。
 * home-link/MCP/AGENTS.md brief 属后续 PR（见 docs/plan/MULTI-CLI-RUNNER.md）。</p>
 *
 * @author sei-online-code
 */
public final class CodexSandboxConfig {

    static final String BEGIN_MARKER = "# BEGIN sei-managed (do not edit; regenerated by CodexSandboxConfig)";
    static final String END_MARKER = "# END sei-managed";

    private CodexSandboxConfig() {
    }

    /**
     * 在给定 codex-home 下写/重写托管沙箱块。
     *
     * @param codexHome per-run CODEX_HOME 目录（不存在则创建）
     * @param logger    日志器（darwin 回退时 warn）
     * @throws IOException 读写 config.toml 失败
     */
    public static void write(Path codexHome, Logger logger) throws IOException {
        Files.createDirectories(codexHome);
        Path config = codexHome.resolve("config.toml");
        String existing = Files.exists(config) ? Files.readString(config, StandardCharsets.UTF_8) : "";
        String stripped = stripManagedBlock(existing);
        stripped = stripSkillsConfig(stripped);
        String block = buildBlock(logger);
        String content = block + "\n" + stripped;
        Files.writeString(config, content, StandardCharsets.UTF_8);
    }

    /** 是否走 darwin（macOS）的 danger-full-access 回退策略。包级可见便于测试。 */
    static boolean isDarwin() {
        String os = System.getProperty("os.name", "");
        String lower = os.toLowerCase();
        return lower.contains("mac") || lower.contains("darwin");
    }

    private static String buildBlock(Logger logger) {
        StringBuilder sb = new StringBuilder();
        sb.append(BEGIN_MARKER).append('\n');
        // PR2 #1/#2：禁用 memory（防跨任务记忆泄漏，multica#3130）与 multi_agent
        // （防子 agent 未结束即触发 turn/completed）。用 dotted key 置 [sandbox_workspace_write]
        // 段头之前，避开 TOML「top-level key 须先于 table header」次序约束。
        sb.append("features.memories = false\n");
        sb.append("features.multi_agent = false\n");
        sb.append("memories.generate_memories = false\n");
        sb.append("memories.use_memories = false\n");
        if (isDarwin()) {
            sb.append("sandbox_mode = \"danger-full-access\"\n");
            if (logger != null) {
                logger.warn("codex sandbox: darwin 检测到，回退 danger-full-access（openai/codex#10390）");
            }
        } else {
            sb.append("sandbox_mode = \"workspace-write\"\n");
            sb.append("[sandbox_workspace_write]\n");
            sb.append("network_access = true\n");
        }
        sb.append(END_MARKER);
        return sb.toString();
    }

    /** 剥离既有托管块（含其后同行到 END_MARKER 行）。幂等。 */
    private static String stripManagedBlock(String content) {
        int begin = content.indexOf(BEGIN_MARKER);
        if (begin < 0) {
            return content;
        }
        int end = content.indexOf(END_MARKER, begin);
        if (end < 0) {
            // 无 END 异常：剥到串尾
            return content.substring(0, begin);
        }
        int lineEnd = content.indexOf('\n', end);
        String after = lineEnd >= 0 ? content.substring(lineEnd + 1) : "";
        return content.substring(0, begin) + after;
    }

    /**
     * 剥离用户 config.toml 中的 {@code [[skills.config]]} 数组表段（PR2 #3）。参考 multica
     * {@code codex_skill_strip.go}。
     *
     * <p>WHY：Codex Desktop 写入 plugin-backed skills 的 {@code [[skills.config]]} 段缺
     * {@code path} 字段，codex CLI 0.114 的 TOML 解析器拒收，致 per-run 启动失败。段从
     * {@code [[skills.config]]} 行起到下一表头（{@code [...]} / {@code [[...]]}）或串尾止。</p>
     *
     * <p>仅作用于用户内容——调用前 {@link #stripManagedBlock} 已先行剥离托管块。</p>
     *
     * @param content 已剥托管块的用户 config.toml 文本
     * @return 移除全部 {@code [[skills.config]]} 段后的文本
     */
    static String stripSkillsConfig(String content) {
        StringBuilder out = new StringBuilder();
        boolean skipping = false;
        for (String line : content.split("\n", -1)) {
            boolean isHeader = line.trim().startsWith("[");
            if (isHeader) {
                // 任一表头终止当前跳过段；[[skills.config]] 自身则（重新）进入跳过。
                skipping = line.trim().startsWith("[[skills.config]]");
            }
            if (skipping) {
                continue;
            }
            if (out.length() > 0) {
                out.append('\n');
            }
            out.append(line);
        }
        return out.toString();
    }

    /**
     * 播种用户 skills 到 per-run codex-home（PR2 #4）。参考 multica {@code codex_user_skills.go}。
     *
     * <p>WHY：codex CLI 从 {@code CODEX_HOME/skills/} 加载用户 skills；per-run 隔离的 CODEX_HOME
     * 默认空，agent 失去用户已装 skills。将 {@code ~/.codex/skills/} 递归拷入 per-run，让 codex
     * 发现既有 skills 而不污染用户家目录。</p>
     *
     * <p>best-effort：源目录不存在（用户未装 skills）直接返回；遍历/拷贝失败仅 warn 不抛——
     * skills 缺失不阻断 codex 运行，仅损失能力。</p>
     *
     * @param codexHome per-run CODEX_HOME
     * @param logger    日志器（可为 null）
     */
    public static void seedUserSkills(Path codexHome, Logger logger) {
        String home = System.getProperty("user.home");
        if (home == null || home.isBlank()) {
            return;
        }
        seedUserSkills(codexHome, Path.of(home), logger);
    }

    /**
     * 包级可见重载，接受 {@code userHome} 便于测试注入临时家目录。
     *
     * @param codexHome per-run CODEX_HOME
     * @param userHome  用户家目录（取 {@code .codex/skills} 子树）
     * @param logger    日志器（可为 null）
     */
    static void seedUserSkills(Path codexHome, Path userHome, Logger logger) {
        Path source = userHome.resolve(".codex/skills");
        if (!Files.isDirectory(source)) {
            return;
        }
        Path target = codexHome.resolve("skills");
        try (Stream<Path> walk = Files.walk(source)) {
            walk.forEach(src -> {
                Path dst = target.resolve(source.relativize(src));
                try {
                    if (Files.isDirectory(src)) {
                        Files.createDirectories(dst);
                    } else {
                        Files.createDirectories(dst.getParent());
                        Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
                    }
                } catch (IOException e) {
                    if (logger != null) {
                        logger.warn("codex user_skills 拷贝失败 src={}", src, e);
                    }
                }
            });
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex user_skills 遍历失败 source={}", source, e);
            }
        }
    }
}
