package com.changhong.onlinecode.agent;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Codex 沙箱配置写入器（PR1）。参考 multica
 * {@code server/internal/daemon/execenv/codex_sandbox.go} 的 managed-block 模型。
 *
 * <p>在 per-run {@code CODEX_HOME/config.toml} 顶部写一个 marker 分隔的托管块，
 * 幂等（已存在则先剥后写），marker 之外的用户内容保留。policy 按平台分流：</p>
 * <ul>
 *   <li>非-darwin（Linux 等）：{@code sandbox_mode="workspace-write"} + {@code [sandbox_workspace_write] network_access=true}。
 *       Linux Landlock 不受 macOS Seatbelt 的 network_access 静默忽略 bug 影响。</li>
 *   <li>darwin：{@code sandbox_mode="danger-full-access"}。因 openai/codex#10390——
 *       macOS Seatbelt 在 workspace-write 模式下静默忽略 network_access=true，
 *       DNS 在 syscall 层被拦，agent 无法触达外部 API，故回退全访问。</li>
 * </ul>
 *
 * <p>PR1 写 sandbox 块；PR2 增补 memory/multi_agent 禁用键（{@link #buildBlock}）、
 * skill_strip（{@link #stripSkillsConfig}）、user_skills 播种（{@link #seedUserSkills}）。
 * PR3 增补 home 符号链接树（{@link #linkSharedHome}）与 MCP 托管块（{@link #writeMcpBlock}）。
 * AGENTS.md brief 属 service 层（{@link AgentBriefWriter}）。见 docs/plan/MULTI-CLI-RUNNER.md。</p>
 *
 * @author sei-online-code
 */
public final class CodexSandboxConfig {

    static final String BEGIN_MARKER = "# BEGIN sei-managed (do not edit; regenerated by CodexSandboxConfig)";
    static final String END_MARKER = "# END sei-managed";

    /** MCP 托管块 marker（PR3 #6）。与 sandbox marker 模式一致，便于 ops grep 所有托管块。 */
    static final String MCP_BEGIN_MARKER = "# BEGIN sei-managed mcp_servers (do not edit; regenerated by CodexSandboxConfig)";
    static final String MCP_END_MARKER = "# END sei-managed mcp_servers";

    /** 匹配用户 config.toml 中的 {@code [mcp_servers.<name>]} 表头（含 quoted-key 形式）。 */
    private static final Pattern USER_MCP_TABLE_HEADER = Pattern.compile(
            "^\\s*\\[\\s*mcp_servers\\s*\\.\\s*(?:\"[^\"]*\"|[^\\]\\s]+)\\s*\\]\\s*(?:#.*)?$");

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private CodexSandboxConfig() {
    }

    /**
     * 在给定 codex-home 下写/重写托管沙箱块。
     *
     * @param codexHome per-run CODEX_HOME 目录（不存在则创建）
     * @param logger    日志器（darwin 回退时 warn）
     * @throws IOException 读写 config.toml 失败
     */
    public static void write(Path codexHome, Logger logger) throws IOException {
        Files.createDirectories(codexHome);
        Path config = codexHome.resolve("config.toml");
        String existing = Files.exists(config) ? Files.readString(config, StandardCharsets.UTF_8) : "";
        String stripped = stripManagedBlock(existing);
        stripped = stripSkillsConfig(stripped);
        String block = buildBlock(logger);
        String content = block + "\n" + stripped;
        Files.writeString(config, content, StandardCharsets.UTF_8);
    }

    /** 是否走 darwin（macOS）的 danger-full-access 回退策略。包级可见便于测试。 */
    static boolean isDarwin() {
        String os = System.getProperty("os.name", "");
        String lower = os.toLowerCase();
        return lower.contains("mac") || lower.contains("darwin");
    }

    private static String buildBlock(Logger logger) {
        StringBuilder sb = new StringBuilder();
        sb.append(BEGIN_MARKER).append('\n');
        // PR2 #1/#2：禁用 memory（防跨任务记忆泄漏，multica#3130）与 multi_agent
        // （防子 agent 未结束即触发 turn/completed）。用 dotted key 置 [sandbox_workspace_write]
        // 段头之前，避开 TOML「top-level key 须先于 table header」次序约束。
        sb.append("features.memories = false\n");
        sb.append("features.multi_agent = false\n");
        sb.append("memories.generate_memories = false\n");
        sb.append("memories.use_memories = false\n");
        if (isDarwin()) {
            sb.append("sandbox_mode = \"danger-full-access\"\n");
            if (logger != null) {
                logger.warn("codex sandbox: darwin 检测到，回退 danger-full-access（openai/codex#10390）");
            }
        } else {
            sb.append("sandbox_mode = \"workspace-write\"\n");
            sb.append("[sandbox_workspace_write]\n");
            sb.append("network_access = true\n");
        }
        sb.append(END_MARKER);
        return sb.toString();
    }

    /** 剥离既有托管块（含其后同行到 END_MARKER 行）。幂等。 */
    private static String stripManagedBlock(String content) {
        int begin = content.indexOf(BEGIN_MARKER);
        if (begin < 0) {
            return content;
        }
        int end = content.indexOf(END_MARKER, begin);
        if (end < 0) {
            // 无 END 异常：剥到串尾
            return content.substring(0, begin);
        }
        int lineEnd = content.indexOf('\n', end);
        String after = lineEnd >= 0 ? content.substring(lineEnd + 1) : "";
        return content.substring(0, begin) + after;
    }

    /**
     * 剥离用户 config.toml 中的 {@code [[skills.config]]} 数组表段（PR2 #3）。参考 multica
     * {@code codex_skill_strip.go}。
     *
     * <p>WHY：Codex Desktop 写入 plugin-backed skills 的 {@code [[skills.config]]} 段缺
     * {@code path} 字段，codex CLI 0.114 的 TOML 解析器拒收，致 per-run 启动失败。段从
     * {@code [[skills.config]]} 行起到下一表头（{@code [...]} / {@code [[...]]}）或串尾止。</p>
     *
     * <p>仅作用于用户内容——调用前 {@link #stripManagedBlock} 已先行剥离托管块。</p>
     *
     * @param content 已剥托管块的用户 config.toml 文本
     * @return 移除全部 {@code [[skills.config]]} 段后的文本
     */
    static String stripSkillsConfig(String content) {
        StringBuilder out = new StringBuilder();
        boolean skipping = false;
        for (String line : content.split("\n", -1)) {
            boolean isHeader = line.trim().startsWith("[");
            if (isHeader) {
                // 任一表头终止当前跳过段；[[skills.config]] 自身则（重新）进入跳过。
                skipping = line.trim().startsWith("[[skills.config]]");
            }
            if (skipping) {
                continue;
            }
            if (out.length() > 0) {
                out.append('\n');
            }
            out.append(line);
        }
        return out.toString();
    }

    /**
     * 播种用户 skills 到 per-run codex-home（PR2 #4）。参考 multica {@code codex_user_skills.go}。
     *
     * <p>WHY：codex CLI 从 {@code CODEX_HOME/skills/} 加载用户 skills；per-run 隔离的 CODEX_HOME
     * 默认空，agent 失去用户已装 skills。将 {@code ~/.codex/skills/} 递归拷入 per-run，让 codex
     * 发现既有 skills 而不污染用户家目录。</p>
     *
     * <p>best-effort：源目录不存在（用户未装 skills）直接返回；遍历/拷贝失败仅 warn 不抛——
     * skills 缺失不阻断 codex 运行，仅损失能力。</p>
     *
     * @param codexHome per-run CODEX_HOME
     * @param logger    日志器（可为 null）
     */
    public static void seedUserSkills(Path codexHome, Logger logger) {
        String home = System.getProperty("user.home");
        if (home == null || home.isBlank()) {
            return;
        }
        seedUserSkills(codexHome, Path.of(home), logger);
    }

    /**
     * 包级可见重载，接受 {@code userHome} 便于测试注入临时家目录。
     *
     * @param codexHome per-run CODEX_HOME
     * @param userHome  用户家目录（取 {@code .codex/skills} 子树）
     * @param logger    日志器（可为 null）
     */
    static void seedUserSkills(Path codexHome, Path userHome, Logger logger) {
        Path source = userHome.resolve(".codex/skills");
        if (!Files.isDirectory(source)) {
            return;
        }
        Path target = codexHome.resolve("skills");
        try (Stream<Path> walk = Files.walk(source)) {
            walk.forEach(src -> {
                Path dst = target.resolve(source.relativize(src));
                try {
                    if (Files.isDirectory(src)) {
                        Files.createDirectories(dst);
                    } else {
                        Files.createDirectories(dst.getParent());
                        Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
                    }
                } catch (IOException e) {
                    if (logger != null) {
                        logger.warn("codex user_skills 拷贝失败 src={}", src, e);
                    }
                }
            });
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex user_skills 遍历失败 source={}", source, e);
            }
        }
    }

    /**
     * 链接共享 codex home 资源到 per-run CODEX_HOME（PR3 #5）。参考 multica
     * {@code codex_home.go} + {@code codex_home_link.go}。
     *
     * <p>WHY：per-run CODEX_HOME 是隔离临时区，默认不含 auth.json/sessions/ 等。
     * codex 认证需 auth.json、会话日志写 sessions/、插件缓存读 plugins/cache——全部
     * 从共享 {@code ~/.codex/}（或 {@code $CODEX_HOME}）符号链接进来，让 per-run 跟踪
     * 共享状态（token 刷新、会话可见性、插件复用）而不污染共享家目录。instructions.md /
     * config.json 走隔离拷贝（per-run 修改不回传共享）。config.toml 不在此处理——已由
     * {@link #write} 托管。</p>
     *
     * <p>best-effort：符号链接失败（如 Windows 无权限）文件回退拷贝、目录 warn no-op，
     * 不阻断 codex 运行。</p>
     *
     * @param codexHome per-run CODEX_HOME（须已存在，由 {@link #write} 创建）
     * @param logger    日志器（可为 null）
     */
    public static void linkSharedHome(Path codexHome, Logger logger) {
        linkSharedHome(codexHome, resolveSharedCodexHome(), logger);
    }

    /**
     * 包级可见重载，接受 {@code sharedHome} 便于测试注入临时共享家目录。
     *
     * @param codexHome  per-run CODEX_HOME
     * @param sharedHome 共享 codex 家目录（取 auth.json/sessions/plugins/cache/instructions.md/config.json）
     * @param logger     日志器（可为 null）
     */
    static void linkSharedHome(Path codexHome, Path sharedHome, Logger logger) {
        // 共享符号链接：auth.json（文件）、sessions/（目录）、plugins/cache（目录）
        ensureFileLink(sharedHome.resolve("auth.json"), codexHome.resolve("auth.json"), logger);
        ensureDirLink(sharedHome.resolve("sessions"), codexHome.resolve("sessions"), logger);
        ensureDirLink(sharedHome.resolve("plugins/cache"), codexHome.resolve("plugins/cache"), logger);
        // 隔离拷贝：instructions.md、config.json（per-run 修改不回传共享）
        syncCopy(sharedHome.resolve("instructions.md"), codexHome.resolve("instructions.md"), logger);
        syncCopy(sharedHome.resolve("config.json"), codexHome.resolve("config.json"), logger);
    }

    /** 解析共享 codex 家目录：{@code $CODEX_HOME}（JVM env）→ {@code ~/.codex}。 */
    static Path resolveSharedCodexHome() {
        String env = System.getenv("CODEX_HOME");
        if (env != null && !env.isBlank()) {
            return Path.of(env).toAbsolutePath();
        }
        String home = System.getProperty("user.home");
        if (home == null || home.isBlank()) {
            return Path.of(System.getProperty("java.io.tmpdir"), ".codex").toAbsolutePath();
        }
        return Path.of(home, ".codex").toAbsolutePath();
    }

    /**
     * 文件符号链接：src 缺失 no-op；dst 已正确链接 no-op；否则删 dst 重建。失败回退拷贝。
     * 参考 multica {@code ensureSymlink} + {@code createFileLink}（Windows symlink 失败回退拷贝）。
     */
    private static void ensureFileLink(Path src, Path dst, Logger logger) {
        if (!Files.exists(src)) {
            return; // 源缺失（如用户未登录）no-op
        }
        if (isCorrectLink(dst, src)) {
            return;
        }
        try {
            if (Files.exists(dst) || isBrokenLink(dst)) {
                Files.delete(dst); // 删 wrong-target 符号链接或 stale 常规文件
            }
            Files.createDirectories(dst.getParent());
            Files.createSymbolicLink(dst, src.toAbsolutePath());
        } catch (IOException | UnsupportedOperationException e) {
            // 回退拷贝（Windows 无 symlink 权限等）
            try {
                Files.createDirectories(dst.getParent());
                Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ce) {
                if (logger != null) {
                    logger.warn("codex home file link/copy 失败 src={} dst={}", src, dst, ce);
                }
            }
        }
    }

    /**
     * 目录符号链接：源不存在则先 mkdir（codex 会写），dst 已正确链接 no-op，否则删 dst 重建。
     * 参考 multica {@code ensureDirSymlink} + {@code exposeSharedCodexPluginCache}。
     */
    private static void ensureDirLink(Path src, Path dst, Logger logger) {
        try {
            Files.createDirectories(src);
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex home shared dir 创建失败 src={}", src, e);
            }
            return;
        }
        if (isCorrectLink(dst, src)) {
            return;
        }
        try {
            removeLinkOrDir(dst, logger); // 删 wrong 符号链接 / stale 目录（不递归进符号链接目标）
            Files.createDirectories(dst.getParent());
            Files.createSymbolicLink(dst, src.toAbsolutePath());
        } catch (IOException | UnsupportedOperationException e) {
            if (logger != null) {
                logger.warn("codex home dir link 失败 src={} dst={}", src, dst, e);
            }
        }
    }

    /**
     * 隔离拷贝：src 存在→刷新拷贝；src 缺失→删 dst（不残留 stale 拷贝）。参考 multica {@code syncCopiedFile}。
     * WHY refresh：避免 per-run config.json/instructions.md 卡在首次播种快照（multica MUL-2646）。
     */
    private static void syncCopy(Path src, Path dst, Logger logger) {
        if (Files.exists(dst) || isBrokenLink(dst)) {
            try {
                Files.delete(dst);
            } catch (IOException e) {
                if (logger != null) {
                    logger.warn("codex home syncCopy 删 stale dst 失败 dst={}", dst, e);
                }
                return;
            }
        }
        if (!Files.exists(src)) {
            return; // 共享源已移除，per-run stale 拷贝须随同消失
        }
        try {
            Files.createDirectories(dst.getParent());
            Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex home syncCopy 拷贝失败 src={} dst={}", src, dst, e);
            }
        }
    }

    /** dst 是否为指向 src（绝对路径）的符号链接。 */
    private static boolean isCorrectLink(Path dst, Path src) {
        if (!Files.isSymbolicLink(dst)) {
            return false;
        }
        try {
            return Files.readSymbolicLink(dst).equals(src.toAbsolutePath());
        } catch (IOException e) {
            return false;
        }
    }

    /** dst 是否为断链（符号链接但 target 不存在）。 */
    private static boolean isBrokenLink(Path dst) {
        return Files.isSymbolicLink(dst) && !Files.exists(dst);
    }

    /**
     * 删除符号链接或真实目录/文件。<b>不递归进入符号链接目标</b>——符号链接直接 {@link Files#delete}
     * （仅删链接），仅真实目录走 walk 递归。WHY：{@link Files#walk} 会跟随符号链接，对指向共享
     * sessions/ 的链接 walk 会误删共享家目录内容。
     */
    private static void removeLinkOrDir(Path p, Logger logger) {
        if (Files.isSymbolicLink(p)) {
            try {
                Files.delete(p);
            } catch (IOException e) {
                if (logger != null) {
                    logger.warn("codex home removeLinkOrDir 删符号链接失败 path={}", p, e);
                }
            }
            return;
        }
        if (!Files.exists(p)) {
            return;
        }
        try (Stream<Path> walk = Files.walk(p)) {
            walk.sorted(Comparator.reverseOrder()).forEach(x -> {
                try {
                    Files.deleteIfExists(x);
                } catch (IOException ignored) {
                    // 残留由 OS 临时区兜底
                }
            });
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex home removeLinkOrDir 递归删失败 path={}", p, e);
            }
        }
    }

    /**
     * 写/清 {@code config.toml} 的 {@code [mcp_servers.*]} 托管块（PR3 #6）。参考 multica
     * {@code pkg/agent/codex.go:ensureCodexMcpConfig}。
     *
     * <p>WHY 走文件而非 argv：{@code mcp_servers.<id>.env} 可载 secrets（API key/bearer），
     * 进程 argv 会出现在 OS {@code ps} 与 daemon 日志，泄露 redacted 字段。写入 0o600 config.toml
     * 让 secrets 留在 daemon owner lane。托管块为权威源——managed 时剥用户全局 {@code [mcp_servers.*]}
     * 表（防 TOML 重定义崩溃 + strict 语义，对齐 claude {@code --strict-mcp-config}）。</p>
     *
     * <p>幂等：先剥既有托管块再渲染。{@code mcpConfig} null/blank → 仅剥既有块（CLI 默认回退）；
     * {@code "{}"} → 写空 marker 块（pin "managed but empty"，strict 禁用户全局）。</p>
     *
     * @param codexHome  per-run CODEX_HOME（config.toml 须已由 {@link #write} 创建）
     * @param mcpConfig  Claude 风格 {@code {"mcpServers":{...}}} JSON；null/blank = 不托管
     * @param logger     日志器（可为 null）
     * @throws IOException config.toml 读写失败，或 mcpConfig JSON 畸形/含非法 TOML 值
     */
    public static void writeMcpBlock(Path codexHome, String mcpConfig, Logger logger) throws IOException {
        Path config = codexHome.resolve("config.toml");
        String existing = Files.exists(config) ? Files.readString(config, StandardCharsets.UTF_8) : "";

        // 始终剥既有托管块（rerun / clear 收敛到干净态）
        String stripped = stripMcpManagedBlock(existing);

        boolean managed = hasManagedCodexMcpConfig(mcpConfig);
        String block = managed ? renderCodexMcpServersBlock(mcpConfig) : null;

        String updated;
        if (managed) {
            // 托管：剥用户 [mcp_servers.*] 表（含子表），防 TOML 重定义 + strict
            stripped = stripCodexUserMcpServerTables(stripped);
            stripped = stripTrailingNewlines(stripped);
            // 空集仍写 marker 块（pin "managed but empty" 于磁盘，下次可剥）
            String blockText = (block != null) ? block : (MCP_BEGIN_MARKER + "\n" + MCP_END_MARKER + "\n");
            updated = stripped.isEmpty() ? blockText : stripped + "\n\n" + blockText;
        } else {
            // 不托管：仅剥既有托管块，留用户表（CLI 默认回退）
            updated = stripped;
        }

        if (updated.equals(existing)) {
            return;
        }
        Files.writeString(config, updated, StandardCharsets.UTF_8);
        setOwnerOnlyPermissions(config, logger);
        if (logger != null) {
            logger.debug("codex: wrote managed mcp_servers block to config.toml managed={}", managed);
        }
    }

    /** {@code mcpConfig} 是否为「托管」态：非 null/非 blank/非字面 "null"（API 三态语义）。 */
    static boolean hasManagedCodexMcpConfig(String raw) {
        if (raw == null) {
            return false;
        }
        String trimmed = raw.trim();
        return !trimmed.isEmpty() && !"null".equals(trimmed);
    }

    /**
     * 渲染 mcpConfig JSON 为 {@code [mcp_servers.*]} TOML 托管块（BEGIN/END marker 包裹）。
     * 参考 multica {@code renderCodexMcpServersBlock}。返回 null 表示无 server 可渲染
     * （空/null mcp_config）。
     */
    static String renderCodexMcpServersBlock(String mcpConfig) throws IOException {
        if (mcpConfig == null || mcpConfig.isBlank()) {
            return null;
        }
        JsonNode root = MAPPER.readTree(mcpConfig);
        JsonNode servers = root.path("mcpServers");
        if (!servers.isObject() || servers.isEmpty()) {
            return null;
        }
        List<String> names = new ArrayList<>();
        servers.fieldNames().forEachRemaining(names::add);
        Collections.sort(names);

        StringBuilder sb = new StringBuilder();
        sb.append(MCP_BEGIN_MARKER).append('\n');
        for (int i = 0; i < names.size(); i++) {
            String name = names.get(i);
            if (!isCodexBareTomlKey(name)) {
                throw new IOException("mcp server name " + name
                        + " must be ASCII alphanumeric / _ / - (Codex bare-key)");
            }
            JsonNode serverVal = servers.get(name);
            if (!serverVal.isObject()) {
                throw new IOException("mcp_servers." + name + " must be a JSON object");
            }
            serverVal = normalizeCodexMcpServerConfig((ObjectNode) serverVal);
            if (i > 0) {
                sb.append('\n');
            }
            sb.append("[mcp_servers.").append(name).append("]\n");
            List<String> keys = new ArrayList<>();
            serverVal.fieldNames().forEachRemaining(keys::add);
            Collections.sort(keys);
            for (String k : keys) {
                sb.append(codexTOMLKey(k)).append(" = ")
                        .append(jsonValueToCodexTOMLInline(serverVal.get(k))).append('\n');
            }
        }
        sb.append(MCP_END_MARKER).append('\n');
        return sb.toString();
    }

    /**
     * 归一化 remote HTTP MCP server 配置：丢弃 {@code type}、{@code headers}→{@code http_headers}
     * （若未存在）、置 {@code experimental_use_rmcp_client=true}。stdio server 原样返回。
     */
    private static JsonNode normalizeCodexMcpServerConfig(ObjectNode server) {
        if (!isCodexRemoteMcpServer(server)) {
            return server;
        }
        ObjectNode normalized = MAPPER.createObjectNode();
        boolean hasHttpHeaders = server.has("http_headers");
        java.util.Iterator<java.util.Map.Entry<String, JsonNode>> it = server.fields();
        while (it.hasNext()) {
            java.util.Map.Entry<String, JsonNode> e = it.next();
            switch (e.getKey()) {
                case "type":
                    continue;
                case "headers":
                    if (!hasHttpHeaders) {
                        normalized.set("http_headers", e.getValue());
                    }
                    break;
                default:
                    normalized.set(e.getKey(), e.getValue());
            }
        }
        normalized.put("experimental_use_rmcp_client", true);
        return normalized;
    }

    private static boolean isCodexRemoteMcpServer(JsonNode server) {
        JsonNode typ = server.get("type");
        if (typ != null && typ.isTextual() && "http".equalsIgnoreCase(typ.asText())) {
            return true;
        }
        return server.has("url") && !server.has("command");
    }

    /**
     * 剥离用户 config.toml 中的 {@code [mcp_servers.*]} 表（表头 + 段体到下一表头/串尾），
     * 含子表（{@code [mcp_servers.x.env]}）。参考 multica {@code stripCodexUserMcpServerTables}。
     */
    static String stripCodexUserMcpServerTables(String content) {
        List<String> out = new ArrayList<>();
        boolean skipping = false;
        for (String line : content.split("\n", -1)) {
            if (USER_MCP_TABLE_HEADER.matcher(line).matches()) {
                skipping = true;
                continue;
            }
            if (skipping) {
                String trimmed = line.trim();
                if (trimmed.startsWith("[")) {
                    // 下一表头：仍是 mcp_servers.* 表（含子表）则继续跳过；否则停止并 emit
                    if (USER_MCP_TABLE_HEADER.matcher(line).matches()
                            || trimmed.startsWith("[mcp_servers.")
                            || trimmed.startsWith("[ mcp_servers.")) {
                        continue;
                    }
                    skipping = false;
                    out.add(line);
                    continue;
                }
                continue; // 段内行，跳过
            }
            out.add(line);
        }
        return String.join("\n", out);
    }

    /** 剥离既有 MCP 托管块（BEGIN..END）。幂等，与 {@link #stripManagedBlock} 同构。 */
    private static String stripMcpManagedBlock(String content) {
        int begin = content.indexOf(MCP_BEGIN_MARKER);
        if (begin < 0) {
            return content;
        }
        int end = content.indexOf(MCP_END_MARKER, begin);
        if (end < 0) {
            return content.substring(0, begin);
        }
        int lineEnd = content.indexOf('\n', end);
        String after = lineEnd >= 0 ? content.substring(lineEnd + 1) : "";
        return content.substring(0, begin) + after;
    }

    private static String stripTrailingNewlines(String s) {
        return s.replaceAll("\n+$", "");
    }

    /** JSON 值 → TOML inline 值（string/bool/number/array/inline-table）。null 拒收（TOML 无 null）。 */
    private static String jsonValueToCodexTOMLInline(JsonNode v) throws IOException {
        if (v == null || v.isNull()) {
            throw new IOException("null is not a valid TOML value");
        }
        if (v.isBoolean()) {
            return v.asBoolean() ? "true" : "false";
        }
        if (v.isIntegralNumber()) {
            return String.valueOf(v.asLong());
        }
        if (v.isNumber()) {
            return v.asText();
        }
        if (v.isTextual()) {
            return codexTOMLBasicString(v.asText());
        }
        if (v.isArray()) {
            StringBuilder sb = new StringBuilder("[");
            for (int i = 0; i < v.size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                sb.append(jsonValueToCodexTOMLInline(v.get(i)));
            }
            sb.append("]");
            return sb.toString();
        }
        if (v.isObject()) {
            StringBuilder sb = new StringBuilder("{ ");
            List<String> keys = new ArrayList<>();
            v.fieldNames().forEachRemaining(keys::add);
            Collections.sort(keys);
            for (int i = 0; i < keys.size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                sb.append(codexTOMLKey(keys.get(i))).append(" = ")
                        .append(jsonValueToCodexTOMLInline(v.get(keys.get(i))));
            }
            sb.append(" }");
            return sb.toString();
        }
        throw new IOException("unsupported JSON value type: " + v.getNodeType());
    }

    private static String codexTOMLBasicString(String s) {
        StringBuilder sb = new StringBuilder(s.length() + 2);
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\': sb.append("\\\\"); break;
                case '"': sb.append("\\\""); break;
                case '\b': sb.append("\\b"); break;
                case '\t': sb.append("\\t"); break;
                case '\n': sb.append("\\n"); break;
                case '\f': sb.append("\\f"); break;
                case '\r': sb.append("\\r"); break;
                default:
                    if (c < 0x20 || c == 0x7f) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append('"');
        return sb.toString();
    }

    private static String codexTOMLKey(String s) {
        return isCodexBareTomlKey(s) ? s : codexTOMLBasicString(s);
    }

    private static boolean isCodexBareTomlKey(String s) {
        if (s == null || s.isEmpty()) {
            return false;
        }
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                    || (c >= '0' && c <= '9') || c == '_' || c == '-')) {
                return false;
            }
        }
        return true;
    }

    /**
     * 设 0o600（owner-only）权限。WHY：{@code mcp_servers.<id>.env} 可载 secrets，须防 world-readable。
     * 非 POSIX（Windows）跳过；IO 失败 best-effort warn。
     */
    private static void setOwnerOnlyPermissions(Path path, Logger logger) {
        try {
            Set<PosixFilePermission> perms = EnumSet.of(
                    PosixFilePermission.OWNER_READ,
                    PosixFilePermission.OWNER_WRITE);
            Files.setPosixFilePermissions(path, perms);
        } catch (UnsupportedOperationException e) {
            // 非 POSIX 文件系统（Windows）—— 跳过
        } catch (IOException e) {
            if (logger != null) {
                logger.warn("codex mcp config.toml chmod 0600 失败 path={}", path, e);
            }
        }
    }
}
