ALTER TABLE oc_run
    ADD COLUMN IF NOT EXISTS agent_id VARCHAR(36),
    ADD COLUMN IF NOT EXISTS agent_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cli_tool VARCHAR(32),
    ADD COLUMN IF NOT EXISTS model VARCHAR(100),
    ADD COLUMN IF NOT EXISTS input_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS output_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS cache_read_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS cache_write_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS total_tokens BIGINT,
    ADD COLUMN IF NOT EXISTS usage_status VARCHAR(20) NOT NULL DEFAULT 'UNAVAILABLE',
    ADD COLUMN IF NOT EXISTS raw_usage_json TEXT;

CREATE INDEX IF NOT EXISTS idx_run_agent
    ON oc_run (agent_id)
    WHERE agent_id IS NOT NULL;
